# Site settings
author: Jamie M. Brown
title: Web Developer in Progress
header-img: img/home-bg.png
email: jmbrowncow@gmail.com
copyright_name: Jamie M. Brown
description: > # this means to ignore newlines until "baseurl:"
  My journey as a full-stack web developer.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BrownCow371

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
